apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: cassandra-db
  name: cassandra-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cassandra-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: cassandra-db
    spec:
      containers:
        - env:
            - name: CASSANDRA_PASSWORD
              value: cassandra
            - name: CASSANDRA_USERNAME
              value: cassandra
            - name: HEAP_NEWSIZE
              value: 100M
            - name: MAX_HEAP_SIZE
              value: 512M
          image: cassandra:latest
          name: cassandra
          ports:
            - containerPort: 9042
              protocol: TCP
      hostname: cassandra
      restartPolicy: Always
