apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: control-center
  name: control-center
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: control-center
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: control-center
    spec:
      containers:
        - env:
            - name: CONFLIENT_METRICS_ENABLE
              value: "false"
            - name: CONFLUENT_METRICS_TOPIC_REPLICATION
              value: "1"
            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
              value: broker:29092
            - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
              value: "1"
            - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
              value: "1"
            - name: CONTROL_CENTER_REPLICATION_FACTOR
              value: "1"
            - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
              value: http://schema-registry:8081
            - name: PORT
              value: "9021"
          image: confluentinc/cp-enterprise-control-center:7.4.0
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:9021/health
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: control-center
          ports:
            - containerPort: 9021
              protocol: TCP
      hostname: control-center
      restartPolicy: Always
