apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: scheduler
    spec:
      containers:
        - args:
            - bash
            - -c
            - pip install -r ./requirements.txt && airflow db upgrade && airflow scheduler
          env:
            - name: AIRFLOW_WEBSERVER_SECRET_KEY
              value: this_is_a_very_secured_key
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            - name: EXECUTOR
              value: Sequential
            - name: LOAD_EX
              value: "n"
          image: apache/airflow:2.6.0-python3.9
          name: scheduler
          volumeMounts:
            - mountPath: /opt/airflow/script/entrypoint.sh
              name: scheduler-cm1
              subPath: entrypoint.sh
            - mountPath: /opt/airflow/requirements.txt
              name: scheduler-cm2
              subPath: requirements.txt
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: entrypoint.sh
                path: entrypoint.sh
            name: scheduler-cm1
          name: scheduler-cm1
        - configMap:
            items:
              - key: requirements.txt
                path: requirements.txt
            name: scheduler-cm2
          name: scheduler-cm2
