apiVersion: v1
data:
  entrypoint.sh: |-
    #!/bin/bash
    set -e

    if [ -e "/opt/airflow/requirements.txt" ]; then
      $(command python) pip install --upgrade pip
      $(command -v pip) install --user -r requirements.txt
    fi

    if [ ! -f "/opt/airflow/airflow.db" ]; then
      airflow db init && \
      airflow users create \
        --username admin \
        --firstname admin \
        --lastname admin \
        --role Admin \
        --email admin@example.com \
        --password admin
    fi

    $(command -v airflow) db upgrade

    exec airflow webserver
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: scheduler
  name: scheduler-cm1
