apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 8080
    - name: "7077"
      port: 7077
      targetPort: 7077
  selector:
    io.kompose.service: spark-master
